name: "Ata de Reunião Semanal"
description: Template para documentar atas das reuniões semanais do projeto
title: "Documentar a Xª reunião semanal (Weekly Geral #X) do projeto"
labels: ["docs"]
projects: ["documentation planning"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Documente a reunião semanal do projeto seguindo o padrão estabelecido no arquivo [`meetingMinute_TEMPLATE.md`](https://github.com/ATOM-Robot-Arm-Project/docs/blob/main/standardization/Meetings/meetingMinute_TEMPLATE.md).

        É fundamental que todos os acontecimentos, decisões e encaminhamentos discutidos na reunião sejam registrados de forma detalhada e cuidadosa. Um registro minucioso garante transparência, facilita o acompanhamento do progresso do projeto e assegura que todos os participantes estejam alinhados quanto às ações a serem tomadas.

        **Importante:** Siga as instruções detalhadas em [`meetingMinute_TEMPLATE.md`](https://github.com/ATOM-Robot-Arm-Project/docs/blob/main/standardization/Meetings/meetingMinute_TEMPLATE.md) para garantir a padronização e aprove a redação antes da publicação final.
  - type: input
    id: numero_reuniao
    attributes:
      label: Número da Reunião
      description: Indique o número da reunião (ex: 5)
      placeholder: "5"
    validations:
      required: true
  - type: input
    id: data_reuniao
    attributes:
      label: Data da Reunião
      description: Informe a data da reunião
      placeholder: "21 de maio de 2025"
    validations:
      required: true
  - type: textarea
    id: pautas_discutidas
    attributes:
      label: Pautas Discutidas
      description: Liste as pautas discutidas e tópicos abordados
      placeholder: |
        1. Pauta 1
           - Item 1
           - Item 2
        2. Pauta 2
           - Item 1
           - Item 2
    validations:
      required: true
  - type: textarea
    id: encaminhamentos
    attributes:
      label: Encaminhamentos
      description: Detalhe os encaminhamentos, responsáveis e prazos
      placeholder: |
        - Encaminhamento 1
          - Responsável: Nome
          - Prazo: Data
          - Descrição: ...
        - Encaminhamento 2
          - Responsável: Nome
          - Prazo: Data
          - Descrição: ...
    validations:
      required: true
  - type: textarea
    id: observacoes_finais
    attributes:
      label: Observações Finais
      description: Insira observações ou comentários gerais sobre a reunião
      placeholder: "- "
    validations:
      required: false